### ISSUE TITLE
ACMEv1 EOL

### ISSUE THREAD

**Issue by rjhllr** [lexa-uw/ansible-role-letsencrypt#2]
ACMEv1 [is currently being phased out](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/5), thus leading to an error when trying to use this role:

`TASK [lexa-uw.letsencrypt : Make the request of the Lets Encrypt API] *****************************************************************************************************************************************************************************************
fatal: [host]: FAILED! => {"changed": false, "msg": "Error registering: 403 {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.'}"}
`
The role would need to be adapted to use the ACMEv2 protocol.

**Comment by lexa-uw** [comment]
Resolved with #3 
Feel free to upgrade role to v2.1.0 version.
